var TRAP_OPEN_TIME = 0.2;
var TRAP_CLOSE_TIME = 1.0;
var DOOR_OPEN_TIME = 0.5;
var OLD_PLAYER_DIE_TIME = 2;
var NEW_PLAYER_DELIVERY_TIME = 2;
var ARM_BACK = 3;

var DOOR_OPEN_X = 200;
var TRAP_OPEN_X = 100;
var PLAYER_INITIAL_X = 800;
var PLAYER_INITIAL_Y = 70;

var LIGHT_START = 0;
var LIGHT_END = 2;

var ROUND_LENGTH = 10;
var LAST_ROUND_LENGTH = 10;

var TREMBLE_STRENGTH = 2;
var FINAL_TREMBLE_STRENGTH = 5;
var TREMBLE_SPEED = 50;

var FINAL_DOOR_OPEN_SPEED = 10;
